"""
AI request endpoints.
"""
import httpx
from app.config import settings
from app.database import get_db
from app.dependencies import get_current_user
from app.models import Response as ResponseModel
from app.models import User
from app.schemas import AIRequestSchema, AIResponseSchema
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

router = APIRouter(prefix="/api", tags=["AI Request"])


@router.post("/request", response_model=AIResponseSchema)
async def ai_request(
    request_data: AIRequestSchema,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    AI request endpoint (authenticated).
    Sends query to Cloudflare AI Search and returns response.
    
    Args:
        request_data: AI request with prompt
        current_user: Current authenticated user
        db: Database session
        
    Returns:
        AI response with question and answer
        
    Raises:
        HTTPException: If AI request fails
    """
    try:
        # Prepare Cloudflare AI Search request
        url = f"https://api.cloudflare.com/client/v4/accounts/{settings.cloudflare_account_id}/autorag/rags/{settings.ai_search_name}/ai-search"
        
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {settings.cloudflare_api_token}"
        }
        
        # Get the query text (from either 'question' or 'prompt' field)
        query = request_data.query_text
        
        # System message to guide the AI to return structured probability analysis
        system_message = """You are an expert exoplanet analyst. When analyzing celestial bodies:

1. Review the available data about the celestial body
2. Provide a brief analysis of its characteristics
3. Conclude with your probability assessment

CRITICAL FORMAT REQUIREMENT:
You MUST include the probability percentage in your response using ONE of these formats:
- "the probability is approximately XX%"
- "probability of XX%"
- If you find a koi_score value (0.0 to 1.0), convert it to percentage (multiply by 100)

The probability MUST be a number between 0 and 100.

Example response:
"Based on the koi_score of 0.98, this celestial body shows strong indicators of being an exoplanet. The high score suggests excellent confidence in the detection. The probability is approximately 98%."

If insufficient data is provided, respond with your best analysis but DO NOT include a percentage."""
        
        # Prepare payload for Cloudflare AI Search API
        payload = {
            "query": query,
            "max_num_results": 10,
            "rewrite_query": False,
            "stream": False,
            "system_message": system_message
        }
        
        # Call Cloudflare AI Search API
        async with httpx.AsyncClient() as client:
            response = await client.post(
                url, 
                json=payload, 
                headers=headers, 
                timeout=30.0
            )
            response.raise_for_status()
            ai_result = response.json()
            
            # Extract response from the API result
            if not ai_result.get("success", False):
                raise HTTPException(
                    status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                    detail=f"Cloudflare AI Search returned unsuccessful response: {ai_result.get('errors', 'Unknown error')}"
                )
            
            # Get the generated response text
            ai_response_text = ai_result.get("result", {}).get("response", "")
            
            if not ai_response_text:
                ai_response_text = "No response was generated by the AI model. Please try rephrasing your question."
        
        # Extract probability percentage from response
        probability_percentage = None
        try:
            import re

            # Multiple patterns to extract percentage:
            # 1. "PROBABILITY: XX%" or "Probability: XX%"
            # 2. "probability of... is approximately XX%"
            # 3. "probability... is XX%"
            # 4. "koi_score of 0.XX" (convert to percentage)
            # 5. Just "XX%" at the end of a sentence about probability

            # Try pattern 1: Explicit PROBABILITY: XX%
            probability_match = re.search(r'PROBABILITY:\s*(\d+)%', ai_response_text, re.IGNORECASE | re.MULTILINE)
            
            # Try pattern 2: "is approximately XX%"
            if not probability_match:
                probability_match = re.search(r'is\s+approximately\s+\*\*(\d+)%\*\*', ai_response_text, re.IGNORECASE)
            
            # Try pattern 3: "probability... is XX%"
            if not probability_match:
                probability_match = re.search(r'probability.*?is.*?(\d+)%', ai_response_text, re.IGNORECASE | re.DOTALL)
            
            # Try pattern 4: koi_score of 0.XX (convert to percentage)
            if not probability_match:
                koi_match = re.search(r'koi[_\s]*score.*?(?:of|is)\s+\*\*?(0\.\d+)\*\*?', ai_response_text, re.IGNORECASE | re.DOTALL)
                if koi_match:
                    koi_score = float(koi_match.group(1))
                    percentage_value = int(koi_score * 100)
                    if 0 <= percentage_value <= 100:
                        probability_percentage = percentage_value
            
            # Try pattern 5: Look for XX% near end of text
            if not probability_match and not probability_percentage:
                probability_match = re.search(r'(\d+)%\s*$', ai_response_text, re.MULTILINE)
            
            # Extract percentage from match
            if probability_match and not probability_percentage:
                percentage_str = probability_match.group(1)
                percentage_value = int(percentage_str)
                # Validate range
                if 0 <= percentage_value <= 100:
                    probability_percentage = percentage_value
            
            # Clean up the response text by removing explicit probability lines
            if probability_percentage is not None:
                ai_response_text = re.sub(r'\n*PROBABILITY:\s*\d+%\s*$', '', ai_response_text, flags=re.IGNORECASE | re.MULTILINE).strip()
                
        except Exception as e:
            # If extraction fails, continue without probability
            print(f"Warning: Could not extract probability percentage: {e}")
        
        # Save response to database
        new_response = ResponseModel(
            user_id=current_user.id,
            question=query,
            response=ai_response_text,
            probability_percentage=probability_percentage
        )
        
        db.add(new_response)
        await db.commit()
        await db.refresh(new_response)
        
        return AIResponseSchema(
            question=new_response.question,
            response=new_response.response,
            probability_percentage=new_response.probability_percentage,
            created_at=new_response.created_at
        )
        
    except ValueError as e:
        # Validation error from schema
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except httpx.HTTPStatusError as e:
        # HTTP error from Cloudflare API
        error_detail = f"Cloudflare AI Search API error (HTTP {e.response.status_code})"
        
        if e.response.status_code == 401:
            error_detail = "Cloudflare AI Authentication Error: Invalid API token. Please verify CLOUDFLARE_API_TOKEN in .env file."
        elif e.response.status_code == 403:
            error_detail = "Cloudflare AI Permission Error: API token does not have access to AI Search. Please verify token permissions."
        elif e.response.status_code == 404:
            error_detail = f"Cloudflare AI Search Error: The AI Search '{settings.ai_search_name}' does not exist. Please verify AI_SEARCH_NAME in .env file."
        else:
            try:
                error_data = e.response.json()
                error_detail = f"Cloudflare AI API Error: {error_data.get('errors', [{}])[0].get('message', str(e))}"
            except:
                error_detail = f"Cloudflare AI API Error: {str(e)}"
        
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=error_detail
        )
    except httpx.TimeoutException:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Cloudflare AI Search request timed out. The service may be overloaded or slow to respond."
        )
    except httpx.ConnectError:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Cloudflare AI Connection Error: Unable to connect to Cloudflare AI Search API. Please check your internet connection."
        )
    except httpx.HTTPError as e:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=f"Cloudflare AI Network Error: {str(e)}"
        )
    except HTTPException:
        # Re-raise HTTP exceptions
        raise
    except Exception as e:
        await db.rollback()
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Unexpected error processing AI request: {str(e)}"
        )
